In [1]:
import numpy as np

# Creating a 1-D NumPy array
arr1d = np.array([1, 2, 3, 4, 5])
print("1-D Array:")
print(arr1d)

# Creating a 2-D NumPy array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2-D Array:")
print(arr2d)

# Creating a random 1-D NumPy array
rand_arr = np.random.rand(5)
print("Random Array:")
print(rand_arr)

# Performing element-wise multiplication of two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print("Element-wise multiplication:")
print(result)

# Performing matrix multiplication of two NumPy arrays
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result = np.matmul(mat1, mat2)
print("Matrix multiplication:")
print(result)

# Create a 1D NumPy array
a = np.array([1, 2, 3, 4, 5])

# Create a 2D NumPy array
b = np.array([[1, 2, 3], [4, 5, 6]])

# Use NumPy functions to perform operations on arrays
g = np.sum(b)
h = np.mean(b)
i = np.max(b)
j = np.min(b)

print("Sum of b:", g)
print("Mean of b:", h)
print("Max of b:", i)
print("Min of b:", j)


1-D Array:
[1 2 3 4 5]
2-D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Random Array:
[0.04336587 0.69396016 0.33924699 0.48483387 0.76663072]
Element-wise multiplication:
[ 4 10 18]
Matrix multiplication:
[[19 22]
 [43 50]]
Sum of b: 21
Mean of b: 3.5
Max of b: 6
Min of b: 1
