In [1]:
import numpy as np

array1 = np.arange(8)
print("original array :\n",array1)
# shape array with 2 rows and 4 columns
array2 = np.arange(8).reshape(2,4)
print("array reshaped with 2 rows and 4 columns :\n",array2)

# shape array with 4 rows and 2 columns
array3 = np.arange(8).reshape(4,2)
print("array reshaped with 4 rows and 2 columns :\n",array3)

# Constructs 3D array
array4 = np.arange(8).reshape(2, 2, 2)
print("original array reshaped to 3D :\n",array4)

original array :
 [0 1 2 3 4 5 6 7]
array reshaped with 2 rows and 4 columns :
 [[0 1 2 3]
 [4 5 6 7]]
array reshaped with 4 rows and 2 columns :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
original array reshaped to 3D :
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [2]:
import pandas as pd

data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj', 'Ravi', 'Natasha', 'Riya'],
        'Age': [17, 17, 18, 17, 18, 17, 17],
        'Gender': ['M', 'F', 'M', 'M', 'M', 'F', 'F'],
        'Marks': [90, 76, 'NaN', 74, 65, 'NaN', 71]}

df = pd.DataFrame(data)
print(df)
# Categorize gender
df['Gender'] = df['Gender'].map({'M': 0, 'F': 1}).astype(float)

# Display data
print(df)

      Name  Age Gender Marks
0      Jai   17      M    90
1   Princi   17      F    76
2   Gaurav   18      M   NaN
3     Anuj   17      M    74
4     Ravi   18      M    65
5  Natasha   17      F   NaN
6     Riya   17      F    71
      Name  Age  Gender Marks
0      Jai   17     0.0    90
1   Princi   17     1.0    76
2   Gaurav   18     0.0   NaN
3     Anuj   17     0.0    74
4     Ravi   18     0.0    65
5  Natasha   17     1.0   NaN
6     Riya   17     1.0    71
